# Sets domain1.wip and domain2.wip for the current project
# proxy:
#     domains:
#         - domain1
#         - domain2

http:
    # document_root: public/ # Path to the project document root
    # passthru: index.php # Project passthru index
    port: 8000 # Force the port that will be used to run the server
    preferred_port: 8001 # Preferred HTTP port [default: 8000]
    # p12: path/to/p12_cert # Name of the file containing the TLS certificate to use in p12 format
    # allow_http: true # Prevent auto-redirection from HTTP to HTTPS
    # no_tls: true # Use HTTP instead of HTTPS
    # daemon: true # Run the server in the background
    # use_gzip: true # Toggle GZIP compression

# workers:
  # built-in command that builds and watches front-end assets
  # npm_encore_watch:
  #     cmd: ['npx', 'encore', 'dev', '--watch']
  # npm_encore_watch: ~

  # built-in command that starts messenger consumer
  # messenger_consume_async:
  #     cmd: ['symfony', 'console', 'messenger:consume', 'async']
  #     watch: ['config', 'src', 'templates', 'vendor']
  # messenger_consume_async: ~

  # you can also add your own custom commands
  # build_spa:
      # cmd: ['npm', '--cwd', './spa/', 'dev']

  # auto start Docker compose when starting server (available since Symfony CLI 5.7.0)
  # docker_compose: ~